--<ScriptOptions statementTerminator=";"/>

CREATE TABLE EMP_RAND (
		EMPNO NUMBER(4 , 0) NOT NULL,
		ENAME VARCHAR2(10),
		JOB VARCHAR2(9),
		MGR NUMBER(4 , 0),
		HIREDATE DATE,
		SAL NUMBER(7 , 2),
		COMM NUMBER(7 , 2),
		DEPTNO NUMBER(2 , 0)
	);

CREATE UNIQUE INDEX PK_EMP_RAND ON EMP_RAND (EMPNO ASC);

ALTER TABLE EMP_RAND ADD CONSTRAINT PK_EMP_RAND PRIMARY KEY (EMPNO);

ALTER TABLE EMP_RAND ADD CONSTRAINT FK_DEPTNO_RAND FOREIGN KEY (DEPTNO)
	REFERENCES DEPT (DEPTNO);

