--<ScriptOptions statementTerminator=";"/>

CREATE TABLE EMP_DECODE (
		EMPNO NUMBER(4 , 0) NOT NULL,
		ENAME VARCHAR2(10),
		JOB VARCHAR2(9),
		MGR NUMBER(4 , 0),
		HIREDATE DATE,
		SAL NUMBER(7 , 2),
		COMM NUMBER(7 , 2),
		DEPTNO NUMBER(2 , 0)
	);

CREATE UNIQUE INDEX PK_EMP_DECODE ON EMP_DECODE (EMPNO ASC);

ALTER TABLE EMP_DECODE ADD CONSTRAINT PK_EMP_DECODE PRIMARY KEY (EMPNO);

ALTER TABLE EMP_DECODE ADD CONSTRAINT FK_DEPTNO_DECODE FOREIGN KEY (DEPTNO)
	REFERENCES DEPT (DEPTNO);

