--<ScriptOptions statementTerminator=";"/>

CREATE TABLE EMPLOYEES_HASH (
		EMPLOYEE_SID VARCHAR2(9) NOT NULL,
		FIRST_NAME VARCHAR2(20),
		LAST_NAME VARCHAR2(25) NOT NULL,
		EMAIL VARCHAR2(25) NOT NULL,
		PHONE_NUMBER VARCHAR2(20),
		HIRE_DATE DATE NOT NULL,
		JOB_ID VARCHAR2(10) NOT NULL,
		SALARY NUMBER(8 , 2),
		COMMISSION_PCT NUMBER(3 , 2),
		MANAGER_SID VARCHAR2(9),
		DEPARTMENT_ID NUMBER(4 , 0)
	);

CREATE UNIQUE INDEX EMP_EMAIL_UK_HASH ON EMPLOYEES_HASH (EMAIL ASC);

CREATE INDEX EMP_NAME_IX_HASH ON EMPLOYEES_HASH (LAST_NAME ASC, FIRST_NAME ASC);

CREATE INDEX EMP_DEPARTMENT_IX_HASH ON EMPLOYEES_HASH (DEPARTMENT_ID ASC);

CREATE UNIQUE INDEX EMP_EMP_ID_PK_HASH ON EMPLOYEES_HASH (EMPLOYEE_SID ASC);

CREATE INDEX EMP_JOB_IX_HASH ON EMPLOYEES_HASH (JOB_ID ASC);

CREATE INDEX EMP_MANAGER_IX_HASH ON EMPLOYEES_HASH (MANAGER_SID ASC);

ALTER TABLE EMPLOYEES_HASH ADD CONSTRAINT EMP_EMP_ID_PK_HASH PRIMARY KEY (EMPLOYEE_SID);

ALTER TABLE EMPLOYEES_HASH ADD CONSTRAINT EMP_DEPT_FK_HASH FOREIGN KEY (DEPARTMENT_ID)
	REFERENCES DEPARTMENTS (DEPARTMENT_ID);

ALTER TABLE EMPLOYEES_HASH ADD CONSTRAINT EMP_JOB_FK_HASH FOREIGN KEY (JOB_ID)
	REFERENCES JOBS (JOB_ID);

ALTER TABLE EMPLOYEES_HASH ADD CONSTRAINT EMP_MGNR_FK_HASH FOREIGN KEY (MANAGER_SID)
	REFERENCES EMPLOYEES (EMPLOYEE_SID);

