--<ScriptOptions statementTerminator=";"/>

CREATE TABLE EMP_HASHED (
		EMPNO NUMBER(9, 0) NOT NULL,
		ENAME VARCHAR2(15),
		JOB VARCHAR2(15),
		MGR NUMBER(9 , 0),
		HIREDATE DATE,
		SAL NUMBER(8 , 2),
		COMM NUMBER(8 , 2),
		DEPTNO NUMBER(4 , 0)
	);

CREATE UNIQUE INDEX PK_EMP_HASHED ON EMP_HASHED (EMPNO ASC);

ALTER TABLE EMP_HASHED ADD CONSTRAINT PK_EMP_HASHED PRIMARY KEY (EMPNO);

ALTER TABLE EMP_HASHED ADD CONSTRAINT FK_DEPTNO_HASHED FOREIGN KEY (DEPTNO)
	REFERENCES DEPT (DEPTNO);

