

CREATE TABLE LOCATIONS_ENC (
		LOCATION_ID NUMBER(4 , 0) NOT NULL,
		STREET_ADDRESS VARCHAR2(40),
		POSTAL_CODE VARCHAR2(12),
		CITY VARCHAR2(30) NOT NULL,
		STATE_PROVINCE VARCHAR2(25),
		COUNTRY_ID CHAR(2)
	);

CREATE INDEX LOC_STATE_PROVINCE_IX_ENC ON LOCATIONS_ENC (STATE_PROVINCE ASC);

CREATE INDEX LOC_CITY_IX_ENC ON LOCATIONS_ENC (CITY ASC);

CREATE INDEX LOC_ID_PK_ENC ON LOCATIONS_ENC (LOCATION_ID ASC);

CREATE INDEX LOC_COUNTRY_IX_ENC ON LOCATIONS_ENC (COUNTRY_ID ASC);

ALTER TABLE LOCATIONS_ENC ADD CONSTRAINT LOC_ID_PK_ENC PRIMARY KEY (LOCATION_ID);

ALTER TABLE LOCATIONS_ENC ADD CONSTRAINT LOC_C_ID_FK_ENC FOREIGN KEY (COUNTRY_ID)
	REFERENCES COUNTRIES (COUNTRY_ID)
;

